# Generated by Django 3.2.7 on 2021-09-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf', '0002_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_video', models.CharField(max_length=30, verbose_name='Título do vídeo')),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo_video',
        ),
    ]
