# Generated by Django 3.2.7 on 2021-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf', '0003_auto_20210910_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='depoimento',
            field=models.TextField(blank=True, verbose_name='Depoimento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem_depoimento',
            field=models.ImageField(blank=True, null=True, upload_to='imagemdepoimento/', verbose_name='Imagem do depoimento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nome_depoimento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nome do depoimento'),
        ),
    ]
