# Generated by Django 3.2.7 on 2021-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf', '0004_auto_20210910_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_depoimento', models.ImageField(blank=True, null=True, upload_to='imagemdepoimento/', verbose_name='Imagem do depoimento')),
                ('nome_depoimento', models.CharField(blank=True, max_length=20, verbose_name='Nome do depoimento')),
                ('depoimento', models.TextField(blank=True, verbose_name='Depoimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='depoimento',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='imagem_depoimento',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='nome_depoimento',
        ),
    ]
